version: "3.9"

services:
  backend:
    build: .
    image: film-library:latest
    container_name: film-library-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0.12
    container_name: film-library-database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
